### PR TITLE
Makefile updated for static version

### PR DESCRIPTION
**Pull request by lars18th**
Add changes to generate also the static (.a) version of the library.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

I hope you want to merge this. The objective is to compile a fully static version of the "w_scan_cpp". Anyway it's useful to have both versions (shared and static) of the library available. Don't you think so?

Regards.

**Comment by wirbel-at-vdr-portal** [comment]
Hi Lars,

could you please prepare some changes/addons?

1. rename LIBSTAT to LIBRARY_STATIC

2. the static lib (*.a, *.la) should not be build by default, but only by explicit
   'make static' or similar Makefile target. The reason is, that i don't want to break existing builds
   for distributions, ie. debian or arch.

3. the static lib should be installed only by request, but for example by 'make install-static'.
   Many distributions avoid static libs nowadays, for good reasons. 

5. could you pls add to 'README' the missing chapter 'static builds'? Any change to the
   build system should be documented.

6. could you pls add yourselves to CONTRIBUTORS. 

7. for a static lib, there's currently no version information. What about versioning? Users
   should have a clue about versions. For shared lib there's the '-Wl,-soname,$(LIBRARY_MAJOR)'
   Makefile stuff.

If all issues are solved, your patch should go in.

--Winfried

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Regarding your suggestions, I can't fix all of them. For example:

- Regarding the static name of the library, in Debian-based platforms it's common to have two packages for libraries. One provides the "*.so" files (named "libXXX") and the other the "headers" and ".a" files (named "libXXX-dev"). For the second package, the ".a" file doesn't have any version naming. And the reason is because the headers are for the same version as this file. Therefore, the "correct" filename is the one provided at time.
- In reference to generate the static version with `make static`, and install it with `make install-static`, I'm not sure if it's necessary. I agree to not break anything. However, for a "source" package it's easy to provide both versions because the "ar" tool is available for all platforms.

Futhermore, my objective is to only provide a way to compile this library static. Feel free to change this patch as you wish. It isn't necessary to include me in the contributors. And I agree with any solution that you want to apply. My final goal is to provide a compact and static version of the "w_scan_cpp" tool. And that's the reason to add the static version of this "librepfunc" library.

Regards.

**Comment by wirbel-at-vdr-portal** [comment]
I had to do some changes, for example no index was generated with ranlib and make install did not generate the static lib, required to be installed.

Finished, you can now use 'make install-static'.

Closing.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Great! Thank you to introduce this enhancement. We're now more close to compile a static version of the w_scan_cpp tool.

Regarding to the w_scan_cpp tool: Where I need to write to suggest/share patches? I've writed in https://github.com/wirbel-at-vdr-portal/w_scan_cpp/pulls, but I feel you don't check them. Any idea?

**Comment by wirbel-at-vdr-portal** [comment]
Pls check the README on w_scan_cpp, line 5.

Btw., i commented today on one of those.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

> Pls check the README on w_scan_cpp, line 5.

Lines 5-6:
```
Written by:                  Winfried Koehler <nvdec A.T. quantentunnel D.O.T. de >
Project's homepage:          https://www.gen2vdr.de/wirbel/w_scan_cpp/index2.html
```

And I've readed it. However:
1. This page is in GERMAN, not English.
2. This site seems to not have any DEV section.
3. A Forum is missing too.

Therefore, I suggest to accept (almost) to write comments in the ISSUES section. If you don't want any PR. then you can disable it. I can accept it (but I don't suggest it). So please indicate how you want to receive patches. You prefer to share a diff file with you?

**Comment by wirbel-at-vdr-portal** [comment]
Well, a project written by a **German** with **+90% German speaking users** should be documented in this specific language. Otherwise, the majority of my users cannot read the docs.
google translate helps..

Otherwise, you may visit https://www.linuxtv.org/wiki/index.php/W_scan_cpp for english instructions.


If you want a forum style discussion, pls refer to www.vdr-portal.de. This German speaking forum has an extra English speakers section, exactly for that purpose. You're welcome to join.

see you there,
--w.

**Comment by lars18th** [comment]
> If you want a forum style discussion, pls refer to [www.vdr-portal.de](http://www.vdr-portal.de). This German speaking forum has an extra English speakers section, exactly for that purpose. You're welcome to join.

I'm enrolled in the vdr-portal.de site: https://www.vdr-portal.de/forum/index.php?thread/135776-w-scan-cpp/
Thank you!

However, please consider to change you current rules. Perhaps for "technical only aspects" or "patches only" it will be useful to use the github repositories. But in any case what you prefer. 😉 

And for the idea of "German" only because +90% of users... This is true for VDR, but the "w_scan_cpp" tool is world-ware. I don't think that the ATSC support is for DE, and one CLI tool in english only will be for regular german users. Do you think so? 😄

**Pull request closed without merging**
